# ============= Option Menu =============
^O B	=set_option_next "showBidi"
^O D	=set_option_next "direction"
^O V B  =set_option_next "modebarLocation"
^O V C  =set_option_next "rulerShowsCursor"
^O V ^C =set_option_next "rulerShowsCursor"
^O V F	=set_option_next "flipBidiForHost"
^O V I  =set_option_next "showInvisibles"
^O V tab=set_option_next "showInvisibles"
^O V L  =set_option_next "showLineNumbers"
^O V M  =set_option_next "showMarks"
^O V return =set_option_next "showMarks"
^O V R  =set_option_next "showColumnRuler"
^O M '  =set_option_next "matchIgnoresSingleQuote"
^O M "  =set_option_next "matchIgnoresDoubleQuote"
^O M *  =set_option_next "matchIgnoresSlashStar"
^O M /  =set_option_next "matchIgnoresSlashSlash"
^O M #  =set_option_next "matchIgnoresHash"
^O M -  =set_option_next "matchIgnoresDoubleHyphen"
^O M ;  =set_option_next "matchIgnoresSemicolon"
^O M %  =set_option_next "matchIgnoresPercent"
^O S I	=set_option_next "searchIgnoreCase"
^O S W	=set_option_next "searchWrap"
^O S R	=set_option_next "searchRegex"
^O W	=set_option_next "wordwrap"
^O N	=set_option "syntax"
^O I	=set_option_next "insertMode"
^O X	=set_option_next "syntaxDetect"
^O G M  =set_option_next "macOptionKeys"
^O G return =set_option_next "macOptionKeys"
