# - include this file to restore many keymappings familiar from JOE

[mappings:mew]

# ---- Cursor Nav Backwards Compat ----
^K U	=go_buffer_beg
^K V	=go_buffer_end
# --- Quick Backwards Compatibility ---
^K 1	=set_mark '1'
^K 2	=set_mark '2'
^K 3	=set_mark '3'
^K 4	=set_mark '4'
^K 5	=set_mark '5'
^K 6	=set_mark '6'
^K 7	=set_mark '7'
^K 8	=set_mark '8'
^K 9	=set_mark '9'
^K 0	=set_mark '0'
^K F	=find
^K L	=go_line
# --- Save Backwards Compatibility ---
^K A	=buffer_save_all
^K Q	=buffer_save_all&exit
^K S	=buffer_save
^K X	=buffer_save_all true & exit
^K D	=buffer_save_as
