# ============= Buffer Menu ============
^B L	=buffer_list
^B N	=buffer_new
^B Z	=buffer_close
^B 2	=buffer_clone
^B O	=buffer_open_file
^B R	=buffer_insert_file
^B U	=buffer_undo
^B ~	=buffer_revert

# ============= Save Menu ============
^S A	=buffer_save_all
^S Q	=buffer_save_all&exit
^S S	=buffer_save
^S X	=buffer_save_all true & exit
^S D	=buffer_save_as
