[layout.qwerty]
#
# use | to mark absolute middle, and/or < and > to mark left/right hands
# use || and/or << and >> to mark areas beyond convenient reach
#
row+3="esc  F1  F2  F3  F4  F5  F6||F7  F8  F9  F10  F11  F12     fdel"
row+2="`   1   2   3   4   5<  6  >7   8   9   0>> -   =    del   home"
row+1="tab   q   w   e   r < t | y > u   i   o   p>> [   ]   \    pgup"
row-H="^   a   s   d   f   g | h   j   k   l   ;   '  \"  return>>pgdn"
row-1="S-    z   x   c   v<  b > n   m   ,   .   /   S- >>  up     end"
row-2="^   M-      <       space       >      M- >>  left  down  right"

