@author "mew defaults"

^D	=del_char_next	# unix-style
^G	=del_char_next  # wordstar-style
fdel	=del_char_next
^W	=del_word_beg
^T	=del_word_end
esc w	=del_line_beg
esc t	=del_line_end
^\	=del_line_end|del_line
^Y	=del_line
