@author "mew defaults"

^Q H	=help_toggle
esc X	=cmd
esc y	=kill_ring_yank
esc Y	=kill_ring_pop

S-tab	=nav_prior|smart_unindent
tab	=nav_next|completion|insert '\t'
return	=nav_follow false|accept|insert '\n'
^C	=cancel|buffer_close
^R	=repeat_next
^@	=insert ' '; go_char_prior
esc >	=scroll_right
esc <	=scroll_left

^L	=find_next
^]	=go_match

^_	=buffer_undo
^/	=buffer_undo
^Z	=buffer_redo|buffer_undo
