# ============= Quick Menu ============
@author "mew default"

^Q F	=find
^Q B	=go_block_begin
^Q K	=go_block_end
^Q L	=go_line
^Q N	=go_pos_next
^Q P	=go_pos_prior
^Q M	=go_mark
^Q 1	=go_mark '1'
^Q 2	=go_mark '2'
^Q 3	=go_mark '3'
^Q 4	=go_mark '4'
^Q 5	=go_mark '5'
^Q 6	=go_mark '6'
^Q 7	=go_mark '7'
^Q 8	=go_mark '8'
^Q 9	=go_mark '9'
^Q 0	=go_mark '0'
^Q return	=go_mark
^Q Q M	=set_mark
^Q Q 1	=set_mark '1'
^Q Q 2	=set_mark '2'
^Q Q 3	=set_mark '3'
^Q Q 4	=set_mark '4'
^Q Q 5	=set_mark '5'
^Q Q 6	=set_mark '6'
^Q Q 7	=set_mark '7'
^Q Q 8	=set_mark '8'
^Q Q 9	=set_mark '9'
^Q Q 0	=set_mark '0'
^Q Q return	=set_mark
