# ============= Buffer Menu ============
@author "mew defaults"
help	="keys"
^B help	="keys_buffer"
^B P    =window_prior
^B N    =window_next

^B H    =help_toggle
^B M    =main|memo

^B L	=buffer_list
^B E	=buffer_new
^B O	=buffer_open_file
^B A	=buffer_save_all true
^B X	=buffer_save_all & exit
^B S	=buffer_save
^B W	=buffer_write
^B 2	=buffer_clone
^B R	=buffer_insert_file
^B -	=buffer_undo
^B \=   =buffer_redo
^B ~	=buffer_revert

^B Q    =wiki_find
^B U    =stat_peek_up
^B V    =stat_peek_down
