# ============= Cursor Nav ============
@author "mew defaults"

^J	=go_char_prior
left	=nav_left|go_char_prior
^F	=go_char_next
right	=nav_right|go_char_next

M-j	=go_word_prior
M-left	=go_word_prior
esc j	=go_word_prior
^left	=go_word_prior

esc f	=go_word_next
M-f	=go_word_next
M-right	=go_word_next
^right	=go_word_next

^A	=go_line_beg
home	=go_line_beg
^E	=go_line_end
end	=go_line_end

^P	=nav_up|go_line_prior
up	=nav_up|go_line_prior
^N	=nav_down|go_line_next
down	=nav_down|go_line_next

M-up	=go_page_prior
^U	=go_page_prior
^Q U	=go_buffer_beg
pgup	=go_page_prior
M-down	=go_page_next
^V	=go_page_next|go_line_end
^Q V	=go_buffer_end
pgdn	=go_page_next

M-n	=scroll_line_next
M-p	=scroll_line_prior
M-a	=scroll_left
M-e	=scroll_right
